enum ActionTypes {
    CHANGE_CHIP = 'CHANGE_CHIP',
    CLEAR_GAME = 'CLEAR_GAME',
    UPDATE_TIME = 'UPDATE_TIME',
    SET_LOCK = 'SET_LOCK',
    CLEAR_BET = 'CLEAR_BET',
    UPDATE_BET = 'UPDATE_BET',
    UPDATE_TOTAL_VALUE = 'UPDATE_TOTAL_VALUE',
    UPDATE_WALLET = 'UPDATE_WALLET',
    SET_WINNER = 'SET_WINNER',
    ADD_BANKER_CHIPS = 'ADD_BANKER_CHIPS',
    ADD_PLAYER_CHIPS = 'ADD_PLAYER_CHIPS',
    ADD_TIE_CHIPS = 'ADD_TIE_CHIPS',
    ADD_BANKER_CARD = 'ADD_BANKER_CARD',
    ADD_PLAYER_CARD = 'ADD_PLAYER_CARD',
  }
  
  export default ActionTypes;